### ISSUE TITLE
Error when running evaluation.py

### ISSUE THREAD

**Issue by bluffish** [giandbt/synboost#20]
When running evaluation.py, I get this error. I am running on Ubuntu 18, with bdlb from https://github.com/hermannsblum/bdl-benchmark.

Traceback (most recent call last):
  File "estimator.py", line 332, in <module>
    fs = bdlb.load(benchmark="fishyscapes")
  File "/data/bny220000/projects/driving_uncertainty/venv/lib/python3.8/site-packages/bdlb/core/registered.py", line 55, in load
    return _BENCHMARK_REGISTRY.get(benchmark)(
  File "/data/bny220000/projects/driving_uncertainty/venv/lib/python3.8/site-packages/bdlb/fishyscapes/benchmark.py", line 44, in __init__
    self.download_and_prepare(config)
  File "/data/bny220000/projects/driving_uncertainty/venv/lib/python3.8/site-packages/bdlb/fishyscapes/benchmark.py", line 53, in download_and_prepare
    Fishyscapes(config=config).download_and_prepare()
  File "/data/bny220000/projects/driving_uncertainty/venv/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 523, in download_and_prepare
    self._download_and_prepare(
  File "/data/bny220000/projects/driving_uncertainty/venv/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1244, in _download_and_prepare
    split_generators = self._split_generators(  # pylint: disable=unexpected-keyword-arg
  File "/data/bny220000/projects/driving_uncertainty/venv/lib/python3.8/site-packages/bdlb/fishyscapes/fishyscapes_tfds.py", line 140, in _split_generators
    splits = base_builder._split_generators(base_dl_manager)
  File "/data/bny220000/projects/driving_uncertainty/venv/lib/python3.8/site-packages/tensorflow_datasets/image/cityscapes.py", line 203, in _split_generators
    paths[split] = os.path.join(dl_manager.manual_dir, zip_file)
  File "/data/bny220000/projects/driving_uncertainty/venv/lib/python3.8/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 168, in __get__
    cached = self.fget(obj)  # pytype: disable=attribute-error
  File "/data/bny220000/projects/driving_uncertainty/venv/lib/python3.8/site-packages/tensorflow_datasets/core/download/download_manager.py", line 649, in manual_dir
    raise ValueError('To access `dl_manager.manual_dir`, please set '
ValueError: To access `dl_manager.manual_dir`, please set `MANUAL_DOWNLOAD_INSTRUCTIONS` in your dataset.

**Comment by chensongloose** [comment]
Hi, can you run estimator.py please? Could you please tell me the detailed preparation steps？
Looking forward to your reply！
